name: ci-run-npm

on:
  push:

jobs:
  npm-inst:
    name: run-npm-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - run: npm ci
      working-directory: ./server

    - run: npm run non-interactive-test
      working-directory: ./server
