name: ci-run-npm

on:
  push:

jobs:
  npm-inst:
    name: run-npm-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    
    - run: cd server
    - run: pwd
    - run: ls
    - run: ls server

    - run: cd server
    - run: pwd
    - run: ls
    - run: ls server

    - run: npm ci
    - run: npm run non-interactive-test
